In [14]:
import numpy as np

In [1]:
#1 a
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
arr_1d = np.array([1, 2, 3])

print(arr_2d + arr_1d)

[[11 22 33]
 [41 52 63]]


In [46]:
#1 b
arr_1d= np.array([10, 20])
arr_2d = np.array([[1, 2], [3, 4]])
result = arr_2d * arr_1d.reshape(-1,1) # reshape(-1,1) == [:,np.newaxis] 
print(result)

[[10 20]
 [60 80]]


In [16]:
#2 a
arr = np.arange(1, 25).reshape(2, 3, 4)
print(arr[1,:,:])

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [18]:
#2 b
print(arr[:,:,-1])

[[ 4  8 12]
 [16 20 24]]


In [20]:
#2 c
print(arr[::-1,:,:])

[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [21]:
#2 d
arr[arr % 2 == 0] = -1
print(arr)

[[[ 1 -1  3 -1]
  [ 5 -1  7 -1]
  [ 9 -1 11 -1]]

 [[13 -1 15 -1]
  [17 -1 19 -1]
  [21 -1 23 -1]]]


In [26]:
#3 a
arr = np.array([1, 2, 3, 4, 5, 6])
result= np.repeat(arr, np.where(arr % 2 == 1, 2, 0))
print(result)

[1 1 3 3 5 5]


In [27]:
#3 b
result = np.repeat(arr, arr)
print(result)

[1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6]


In [32]:
#4
arr = np.array([10, 20, 30])
arr=(arr - arr.min()) / (arr.max() - arr.min())
arr

array([0. , 0.5, 1. ])

In [47]:
#5 a
i = np.arange(3) #[0 1 2]
j = np.arange(3).reshape(-1,1) #[[0] [1] [2]] 
result = i*j
print(result)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [56]:
#5 b
arr = np.arange(16).reshape(4, 4)
rows, cols = np.indices(arr.shape)  
arr = np.where(rows == cols, 0, arr) 
print(arr)

[[ 0  1  2  3]
 [ 4  0  6  7]
 [ 8  9  0 11]
 [12 13 14  0]]
